19 Create loading screen with navigation router.
Crutch-and-Rake-Uzhhorod/useful-useless-app pull request #43
Opened 2020-10-04 17:15 UTC by ultrasosok

Created loading screen

2020-10-06 09:46 UTC, BruSD requested changes
fix change request

2020-10-06 09:46 UTC, BruSD commented on lib/ui/global/loader_widget.dart
> +class Loader extends StatefulWidget {
rework to StateLasse widget

2020-10-06 09:46 UTC, BruSD commented on lib/ui/loading_screen.dart
> +
rework to state lasse widget

2020-10-06 09:46 UTC, BruSD commented on lib/global/auth/login_page.dart
> +class UserProvider with ChangeNotifier {
вынести провайдер в отдельный класс

2020-10-06 09:46 UTC, BruSD commented on lib/global/auth/login_page.dart
> +  UN_AUTHENTICATED,
enum можно разместить в файле с provider

2020-10-06 09:46 UTC, BruSD commented on lib/global/auth/login_page.dart
>  class LoginPage extends StatefulWidget {
Rework to state lasse widget

2020-10-06 10:30 UTC, ultrasosok commented on lib/global/auth/login_page.dart
> +class UserProvider with ChangeNotifier {
в отдельный класс или файл?
если в класс тогда в чём проблема с enum

2020-10-08 11:25 UTC, BruSD requested changes
Fix one issue

2020-10-08 11:25 UTC, BruSD commented on lib/src/core/provider/provider.dart
> +import 'package:firebase_auth/firebase_auth.dart';
rename file name from provider.dart to user_provider.dart

to avoid misundferstanding in future

2020-10-08 11:46 UTC, BruSD approved these changes
LGFM

2020-10-08 11:49 UTC, merged