Map Tab 1: Calendar date Piker
Crutch-and-Rake-Uzhhorod/useful-useless-app pull request #55
Opened 2021-02-28 17:53 UTC by Ishchik

2021-02-28 22:36 UTC, weikme requested changes

2021-02-28 22:36 UTC, weikme commented on lib/src/ui/home_screen.dart
>  class HomeScreen extends StatefulWidget {
make it stateless unless stateful is needed

2021-03-01 23:45 UTC, weikme approved these changes
lgfm

2021-03-05 10:36 UTC, BruSD approved these changes
LGFM

2021-03-05 10:44 UTC, merged